### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Band-hi#1]
[Infografía 1 Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Band-hi/files/10768289/Infografia.1.Realidad.Aumentada.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo: 20/20 calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado
